global:
  scrape_interval: 5s  # tần suất quét metrics

scrape_configs:
  - job_name: 'nginx-gateway'
    static_configs:
      - targets: 
        - 'nginx-exporter:9113'
        - 'authservice:2000'
        - 'profileservice:2001'
        - 'taskservice:2002'
